image:
  - Visual Studio 2017

clone_depth: 1
shallow_clone: false

cache:
  - C:\Users\appveyor\.conan -> conanfile.py
  - C:\.conan -> conanfile.py

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  ALSOFT_DRIVERS: null
  PYTHON: "C:\\Python36-x64"
  CMAKE_GENERATOR_BASE: "Visual Studio 15 2017"
  NAME_SUFFIX: "windows"
  USE_CONAN: 1

platform:
  - x64

configuration:
  - RelWithDebInfo

matrix:
  fast_finish: false

clone_folder: C:\projects\openrw

init:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - python --version
  - cmake --version
  - msbuild /version
  - pip3 install conan
  - conan user
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

install:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - for /f %%i in ('git rev-parse HEAD') do set COMMIT_HASH=%%i
  - echo APPVEYOR_REPO_COMMIT=%APPVEYOR_REPO_COMMIT%, COMMIT_HASH=%COMMIT_HASH%
  - if NOT "%APPVEYOR_REPO_COMMIT%" == "%COMMIT_HASH%" echo "Appveyor git hash does not match git checkout hash"
  - git submodule update --init --recursive

build_script:
  - ctest -VV -S "%APPVEYOR_BUILD_FOLDER%/cmake/ctest/script_ci.ctest"

after_build:
  - cd "%APPVEYOR_BUILD_FOLDER%\build"
  - cpack -C %CONFIGURATION% -G TXZ
  - appveyor PushArtifact OpenRW-%COMMIT_HASH:~0,8%.tar.xz
