language: cpp

matrix:
  include:
  - os: linux
    compiler: gcc
    env: NAME="Ubuntu Linux (Latest)" NAME_SUFFIX="ubuntu" TEST_COVERAGE=1
    services: docker
    script:
      - scripts/docker/docker_travis.sh "ubuntu_latest.docker"
  - os: linux
    compiler: clang
    env: NAME="Fedora Linux (Latest)" NAME_SUFFIX="fedora-llvm"
    services: docker
    script:
      - scripts/docker/docker_travis.sh "fedora_latest.docker"
  - os: linux
    compiler: gcc
    env: NAME="Arch Linux (Latest)" NAME_SUFFIX="arch" DEBUG=1
    services: docker
    script:
      - scripts/docker/docker_travis.sh "arch_latest.docker"
  # - os: linux
  #   compiler: gcc
  #   env: NAME="conan" NAME_SUFFIX="conan" USE_CONAN=1
  #   script:
  #     - scripts/docker/docker_travis.sh "conan_base.docker"
  - os: osx
    compiler: clang
    env: NAME="Apple macOS" NAME_SUFFIX="mac"
    osx_image: xcode12.5
    cache:
      directories:
        - $HOME/Library/Caches/Homebrew
    before_cache:
      - brew cleanup
    addons:
      homebrew:
        packages:
          - boost
          - cmake
          - bullet
          - ffmpeg
          - glm
          - openal-soft
          - qt5
          - sdl2
          - jack
          - freetype
    install:
      - export PATH="/usr/local/opt/qt/bin:$PATH"
    script:
      - mkdir -p "$TRAVIS_BUILD_DIR/build"
      - ctest -VV -S "$TRAVIS_BUILD_DIR/cmake/ctest/script_ci.ctest"

notifications:
    email: false
#    irc:
#        channels:
#            - chat.freenode.net#openrw
#        template:
#            - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
